table Country-FullNames
	lineageTag: 83959ea1-4a40-4f8a-9c7e-dbebbccd0599

	column CountryCode
		dataType: string
		lineageTag: 2109fd8d-dff6-4d76-9eda-ea09f1f43aaf
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a52dd384-6701-49f0-b287-7996d3ce6a4c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column GeoKey
		dataType: int64
		formatString: 0
		lineageTag: 4bc23445-7ee7-4548-8dc0-e83be40b32d0
		summarizeBy: count
		sourceColumn: GeoKey

		annotation SummarizationSetBy = Automatic

	partition Country-FullNames = m
		mode: import
		queryGroup: 'Key Tables'
		source =
				let
				    Source = Json.Document(Web.Contents("https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/sdg_01_10?format=JSON&lang=EN")),
				    dimension = Source[dimension],
				    geo = dimension[geo],
				    category = geo[category],
				    label = category[label],
				    #"Converted to Table" = Record.ToTable(label),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "GeoKey"}, {"Value", "Country"}, {"Name", "CountryCode"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([Country] <> "Euro area - 19 countries  (2015-2022)" and [Country] <> "Euro area – 20 countries (from 2023)" and [Country] <> "European Union (EU6-1958, EU9-1973, EU10-1981, EU12-1986, EU15-1995, EU25-2004, EU27-2007, EU28-2013, EU27-2020)" and [Country] <> "European Union - 27 countries (2007-2013)" and [Country] <> "European Union - 28 countries (2013-2020)" and [Country] <> "United Kingdom")),
				    #"Appended Query" = Table.Combine({#"Filtered Rows", #"Country EU_V"})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

