table EU_Goal5
	lineageTag: 8f244e33-cf5a-412e-ab63-bc863096abfe

	column IndicatorValue
		dataType: string
		lineageTag: 9f13aa62-3f6a-4650-8822-5f57ca50c3a3
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		lineageTag: 838421a5-46c7-4610-933b-f8cda537f37c
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5134dd6b-d7a9-4af3-9d24-fc93a3b5216f
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: string
		lineageTag: ed582371-670c-49b8-b3ef-7c728583ffbe
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 298930ed-9672-490e-9dc1-964f06ea2818
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: a4df9a75-0b4b-4675-ba7b-f5a12fc03a92
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age
		dataType: string
		lineageTag: 25e464dd-fe4f-4db8-968a-8eb0da25d102
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column nace_r2
		dataType: string
		lineageTag: 9bdc628e-cae4-4211-81a4-49473901adf0
		summarizeBy: none
		sourceColumn: nace_r2

		annotation SummarizationSetBy = Automatic

	column wstatus
		dataType: string
		lineageTag: c2013600-32a3-4850-9533-b902b5a9214c
		summarizeBy: none
		sourceColumn: wstatus

		annotation SummarizationSetBy = Automatic

	column org_inst
		dataType: string
		lineageTag: f85f70bc-ead0-4375-9e6a-6624d3ad918c
		summarizeBy: none
		sourceColumn: org_inst

		annotation SummarizationSetBy = Automatic

	column prof_pos
		dataType: string
		lineageTag: 5562ceb1-e7c4-4970-849d-b8f5fc16b2e4
		summarizeBy: none
		sourceColumn: prof_pos

		annotation SummarizationSetBy = Automatic

	column M
		dataType: double
		lineageTag: a80d0695-e853-43b0-968f-02c31c56b27b
		summarizeBy: sum
		sourceColumn: M

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column F
		dataType: double
		lineageTag: d25739c5-32f4-44e9-8b63-df8020be9924
		summarizeBy: sum
		sourceColumn: F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: int64
		formatString: 0
		lineageTag: c944c346-40ba-4a92-8bb6-7406dc90f543
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column RecordCount
		dataType: double
		lineageTag: dfb3c30c-9c60-4b1e-9ea6-9092b7a5e8f4
		summarizeBy: sum
		sourceColumn: RecordCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modified
		dataType: dateTime
		formatString: General Date
		lineageTag: d0b7c514-7fd9-4829-923d-4823fc4355bb
		summarizeBy: none
		sourceColumn: Modified

		annotation SummarizationSetBy = Automatic

	column Duplicate
		dataType: string
		lineageTag: 95024ab5-b481-4ef1-94c9-9241458aeec0
		summarizeBy: none
		sourceColumn: Duplicate

		annotation SummarizationSetBy = Automatic

	column CountryIndex
		dataType: double
		lineageTag: f5cc1aab-1fa5-49db-979f-0754d8a8b7d0
		summarizeBy: sum
		sourceColumn: CountryIndex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition EU_Goal5 = m
		mode: import
		queryGroup: 'EU-Goal1\EU_Goal 5'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"ab8970c0-6fe3-4f4a-9cdd-fc18a8cf682b" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 5"]}[Data],
				    Goal5_ = #"ab8970c0-6fe3-4f4a-9cdd-fc18a8cf682b"{[entity="Goal5",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(Goal5_, each ([IndicatorValue] <> "SDG_05_10")),
				    #"Appended Query" = Table.Combine({#"Filtered Rows", EU_SDG_05_10})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

