table EU_Goal10
	lineageTag: 77d14999-222a-4137-8060-4abc11edbe35

	column IndicatorValue
		dataType: string
		lineageTag: 52b599f9-6f31-4417-853b-2d906007f33a
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		lineageTag: e9ae5473-db4a-4ada-b40e-eb2fb7b27083
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: 07e3379d-ceef-4135-9771-85d524f2dd02
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Unit
		dataType: string
		lineageTag: c7453d58-d01c-40dc-b2d2-f8f975cad60f
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: d0f4704b-a0b8-41a7-bda6-3db06e9bfd7d
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: string
		lineageTag: 29c6899f-6ac7-45c8-8857-1a5aa805801c
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

	column na_item
		dataType: string
		lineageTag: b743107c-f193-40a6-8d03-8659ef9f7303
		summarizeBy: none
		sourceColumn: na_item

		annotation SummarizationSetBy = Automatic

	column asyl_app
		dataType: string
		lineageTag: d2687f91-aa4c-49fc-9844-6e597f7b7676
		summarizeBy: none
		sourceColumn: asyl_app

		annotation SummarizationSetBy = Automatic

	column RecordCount
		dataType: double
		lineageTag: cf8aada5-37dc-43f8-bbed-dce662d34172
		summarizeBy: sum
		sourceColumn: RecordCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition EU_Goal10 = m
		mode: import
		queryGroup: 'EU-Goal1\EU_Goal 10'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"01ac67f9-8931-4690-be8c-906c66ded44b" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 10"]}[Data],
				    SDG_10_10_ = #"01ac67f9-8931-4690-be8c-906c66ded44b"{[entity="SDG_10_10",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(SDG_10_10_, each ([na_item] = "VI_PPS_EU27_2020_HAB")),
				    #"Appended Query" = Table.Combine({#"Filtered Rows", SDG_10_41, SDG_10_50, SDG_10_60})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

