table 'EU_SDG_03_60 (2)'
	lineageTag: c06ac1b6-ccf9-404b-9179-30f254e9a9e6

	column CountryAbrv
		dataType: string
		lineageTag: b6355440-d812-49ce-8aa9-dc088fa2c242
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: double
		lineageTag: 8fb4f7ac-73a2-480b-838e-a8a98f12b12d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: string
		lineageTag: 23541c83-89c0-4820-999c-957243502dcf
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 865cad22-0347-475a-b907-bc026d23d794
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 952ded67-d8e3-4301-a7b9-84624e0b4ec6
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 88228267-cf5b-4636-9370-6bdf5b7e8200
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: 579d79a7-c8b7-4496-9bf4-c0775f6181dc
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column IndicatorValue
		dataType: string
		lineageTag: 38b4b5bd-560f-4b00-9df6-f40485f4ca77
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 4ed0aea1-c50e-4118-98f6-275e1f433716
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	partition 'EU_SDG_03_60 (2)' = m
		mode: import
		queryGroup: 'EU-Goal1\EU_Goal 3'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"cde5f2dc-94e1-40b1-9d86-7334a30cc33a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 3"]}[Data],
				    SDG_03_60_ = #"cde5f2dc-94e1-40b1-9d86-7334a30cc33a"{[entity="SDG_03_60",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(SDG_03_60_, each ([sex] = "T"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

