table eu_SDG_13_21
	lineageTag: 6f6abf5f-af6a-4e37-a2c5-3ef20df56191

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2b477688-8d5e-4732-9812-575cee35023d
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: a7a7b1dc-6309-4ad0-8927-18905b2d1e1f
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 25feb6e1-a56a-43ae-891d-ad23514e1d35
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 850acdfd-e68e-4d0d-951f-2fe0b560d1dc
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		lineageTag: 47ea3637-1553-413e-a734-89cc0e0b4572
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		lineageTag: 962d4f1f-c269-49c8-a070-9fd938a73ebf
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	partition eu_SDG_13_21 = m
		mode: import
		queryGroup: EU-Goal1\EU_Goal13
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"4d6c5c1a-98f1-4c86-a450-a994c6460126" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 11 - 12- 13"]}[Data],
				    SDG_13_21_ = #"4d6c5c1a-98f1-4c86-a450-a994c6460126"{[entity="SDG_13_21",version=""]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(#"SDG_13_21_",{"Year", "Unit", "Value", "UpdatedFromDate", "IndicatorValue", "CountryAbrv"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns",{{"Year", Int64.Type}, {"Unit", type text}, {"Value", type number}, {"UpdatedFromDate", type date}, {"IndicatorValue", type text}, {"CountryAbrv", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([Unit] = "T_KM2"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

