table eu_SDG_15_42
	lineageTag: a6d8d141-e919-4c26-9daa-fb2ec7b54210

	column Year
		dataType: double
		lineageTag: 92c8bafc-4b74-4e0f-82a3-e1c8e19a2e6b
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CountryAbrv
		dataType: string
		lineageTag: 63da72d8-df52-4649-889e-6b0e59016327
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 6d4a1971-d0e3-4acc-98fc-81cd0d08fb4c
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 153cfd73-ebe7-4af2-a702-50a010234bcf
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column IndicatorValue
		dataType: string
		lineageTag: 2f1408df-70a4-4335-9826-45bbb78d6c3e
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: aa876b99-f292-4889-9198-471147d8d500
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RecordCount
		dataType: double
		lineageTag: e2e7f78b-f5cf-4c15-af54-eb6e136668aa
		summarizeBy: sum
		sourceColumn: RecordCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition eu_SDG_15_42 = m
		mode: import
		queryGroup: EU_Goal15
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"c1cad8c5-2b2f-4168-a09d-4ca007884a11" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 14 to 17"]}[Data],
				    SDG_15_42_ = #"c1cad8c5-2b2f-4168-a09d-4ca007884a11"{[entity="SDG_15_42",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(SDG_15_42_, each ([Unit] = "PC")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"UpdatedFromDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

