table eu_SDG_10_30
	isHidden
	lineageTag: 22197cd2-cd7a-47c2-922f-8aad9b2771d8

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 09a0aca1-e0f0-4cd5-9997-f1c6f7d5a6db
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		isHidden
		lineageTag: c5168564-5bc1-49b6-aa19-f732cc15cf4a
		summarizeBy: none
		sourceColumn: Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: d633a54e-eb73-4ed0-9b52-126c0cc150f3
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sex
		dataType: string
		isHidden
		lineageTag: e1483ca1-889e-400c-b373-7fafd1198a6b
		summarizeBy: none
		sourceColumn: sex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		isHidden
		lineageTag: 76dc816b-4718-41c7-8f7e-3172fd7b16de
		summarizeBy: none
		sourceColumn: age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 680a52fe-363a-405c-8fed-6a72c628a402
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		isHidden
		lineageTag: fd7b0e75-f402-40a7-a20d-e268f8436ab0
		summarizeBy: none
		sourceColumn: IndicatorValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		isHidden
		lineageTag: a3512a67-717b-4115-9ea7-94fe7efd3f22
		summarizeBy: none
		sourceColumn: CountryAbrv

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column indic_il
		dataType: string
		isHidden
		lineageTag: a7cfcac0-e648-4eab-b35b-d697bcba4bc4
		summarizeBy: none
		sourceColumn: indic_il

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column incgrp
		dataType: string
		lineageTag: bd46589e-7e05-4d4c-a1a6-2db2ea64f753
		summarizeBy: none
		sourceColumn: incgrp

		annotation SummarizationSetBy = Automatic

	column Cities
		dataType: double
		lineageTag: 8f024e90-feb1-4e72-8436-14a8d6629bc7
		summarizeBy: sum
		sourceColumn: Cities

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Towns and suburbs'
		dataType: double
		lineageTag: 67c0292d-24de-4d90-94ae-1bef69f8441b
		summarizeBy: sum
		sourceColumn: Towns and suburbs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rural areas'
		dataType: double
		lineageTag: 27f0d196-cdd2-4102-9d72-fbf08ccbf19f
		summarizeBy: sum
		sourceColumn: Rural areas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedToDate
		dataType: string
		lineageTag: 9956aeaf-0039-4e38-889b-054fb4fae843
		summarizeBy: none
		sourceColumn: UpdatedToDate

		annotation SummarizationSetBy = Automatic

	partition eu_SDG_10_30 = m
		mode: import
		queryGroup: EU-Goal1
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"238281b2-c170-4491-b22a-2ad63536f76a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 1"]}[Data],
				    #"Goal 1_" = #"238281b2-c170-4491-b22a-2ad63536f76a"{[entity="Goal 1",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Goal 1_",{{"Year", Int64.Type}, {"Unit", type text}, {"sex", type text}, {"age", type text}, {"indic_il", type text}, {"CountryAbrv", type text}, {"IndicatorValue", type text},{"UpdatedFromDate", type date}, {"Value", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([IndicatorValue] = "SDG_10_30")),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each true)
				in
				    #"Filtered Rows1"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

