table eu_SDG_01_41
	isHidden
	lineageTag: af08f192-8311-4d3d-af8a-439fbb15a0dc

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: bf7c3eac-754b-49af-a4b7-e43538166af2
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		isHidden
		lineageTag: 49d0dbfd-6153-459d-a3a1-a441171a69b9
		summarizeBy: none
		sourceColumn: Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: 05e8f643-e861-4f16-b24d-f84be3b950ca
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age
		dataType: string
		isHidden
		lineageTag: 59f60419-0e0f-41b2-a958-6c66b6d417f3
		summarizeBy: none
		sourceColumn: age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 5c937006-ee75-44bb-99af-72faf2d7867a
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		isHidden
		lineageTag: e0c96c80-d888-463c-96cc-627f701ef68c
		summarizeBy: none
		sourceColumn: IndicatorValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		isHidden
		lineageTag: 8a46fdda-128b-4ac4-a049-f5cff4d0bf08
		summarizeBy: none
		sourceColumn: CountryAbrv

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column incgrp
		dataType: string
		lineageTag: f39b4e83-f037-4deb-a461-f9c6afb00572
		summarizeBy: none
		sourceColumn: incgrp

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 6711668a-0c55-4baf-8928-12edfd8ac58f
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column indic_il
		dataType: string
		lineageTag: 5ba07fdb-e265-41c8-b962-f648c8d1b766
		summarizeBy: none
		sourceColumn: indic_il

		annotation SummarizationSetBy = Automatic

	column Cities
		dataType: double
		lineageTag: fa204e20-574b-4497-8597-52c8ef68c8d3
		summarizeBy: sum
		sourceColumn: Cities

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Towns and suburbs'
		dataType: double
		lineageTag: afed6e6b-3ad7-490a-a5c4-57ef2bdfdd82
		summarizeBy: sum
		sourceColumn: Towns and suburbs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rural areas'
		dataType: double
		lineageTag: 7330a4eb-7011-4526-b021-a8c48038b289
		summarizeBy: sum
		sourceColumn: Rural areas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedToDate
		dataType: string
		lineageTag: efceff27-7cb2-4762-9efa-d135bdb6de63
		summarizeBy: none
		sourceColumn: UpdatedToDate

		annotation SummarizationSetBy = Automatic

	partition eu_SDG_01_41 = m
		mode: import
		queryGroup: EU-Goal1
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"238281b2-c170-4491-b22a-2ad63536f76a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 1"]}[Data],
				    #"Goal 1_" = #"238281b2-c170-4491-b22a-2ad63536f76a"{[entity="Goal 1",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Goal 1_",{{"Year", Int64.Type}, {"Unit", type text}, {"age", type text}, {"IndicatorValue", type text}, {"Value", type number}, {"UpdatedFromDate", type date},{"CountryAbrv", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([IndicatorValue] = "SDG_01_41"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

