table eu_SDG_01_50
	isHidden
	lineageTag: 8ca09235-79e9-4036-ac1f-c459e0837ce3

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8241abca-358f-4f09-8890-8b48ef93ec4e
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		isHidden
		lineageTag: 3eb336d5-2ab3-4141-a613-2f07e9b26ef4
		summarizeBy: none
		sourceColumn: Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: acc4b96a-6bf8-4f4a-9c5b-5d082a4dae2b
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age
		dataType: string
		isHidden
		lineageTag: aafc8fa9-320b-49f9-a170-7bf1e43bc353
		summarizeBy: none
		sourceColumn: age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 4ec49b0a-a73f-4713-b611-dfce3a6e8688
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		isHidden
		lineageTag: 56eb62a8-a0cc-445f-9d95-49cce68e9aac
		summarizeBy: none
		sourceColumn: IndicatorValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column incgrp
		dataType: string
		isHidden
		lineageTag: baa76b66-1404-4ab4-a18c-77dd2182e8ed
		summarizeBy: none
		sourceColumn: incgrp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		isHidden
		lineageTag: 0c124b25-9116-4dec-bfcc-3250340d3411
		summarizeBy: none
		sourceColumn: CountryAbrv

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: 943f482c-a467-4be7-8de0-02634c831ece
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column indic_il
		dataType: string
		lineageTag: 613b5246-e583-4fcd-af4a-d798006a29e2
		summarizeBy: none
		sourceColumn: indic_il

		annotation SummarizationSetBy = Automatic

	column Cities
		dataType: double
		lineageTag: de5a0a42-7209-446f-a98e-28b74b10321f
		summarizeBy: sum
		sourceColumn: Cities

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Towns and suburbs'
		dataType: double
		lineageTag: add10e18-3ac4-48f6-bb15-9a16fc2aaf3f
		summarizeBy: sum
		sourceColumn: Towns and suburbs

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rural areas'
		dataType: double
		lineageTag: 7abbcbc2-5efd-4e70-a06d-3fc3496eb56d
		summarizeBy: sum
		sourceColumn: Rural areas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedToDate
		dataType: string
		lineageTag: c9e4ad4b-280e-49e2-9d0b-a7a5b02821fd
		summarizeBy: none
		sourceColumn: UpdatedToDate

		annotation SummarizationSetBy = Automatic

	partition eu_SDG_01_50 = m
		mode: import
		queryGroup: EU-Goal1
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"238281b2-c170-4491-b22a-2ad63536f76a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 1"]}[Data],
				    #"Goal 1_" = #"238281b2-c170-4491-b22a-2ad63536f76a"{[entity="Goal 1",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Goal 1_",{ {"Year", Int64.Type}, {"Unit", type text}, {"age", type text}, {"IndicatorValue", type text}, {"Value", type number}, {"UpdatedFromDate", type date}, {"incgrp", type text}, {"CountryAbrv", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([incgrp] = "TOTAL"))
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

