table Goal3
	lineageTag: 40925490-6cd6-4e98-85de-f0ee829a00d3

	measure obs_value_Goal-3 =
			VAR minDate =
			    CALCULATE (
			        MIN ( 'Goal3'[UpdatedFromDate] ),
			        ALLSELECTED ( 'Goal3'[UpdatedFromDate] )
			    )
			VAR maxDate =
			    CALCULATE (
			        MAX ( 'Goal3'[UpdatedFromDate] ),
			        ALLSELECTED ( 'Goal3'[UpdatedFromDate] )
			    )
			VAR minValue =
			    CALCULATE (
			        MIN ( 'Goal3'[Value] )
			    )
			VAR maxValue =
			    CALCULATE (
			        MAX ( 'Goal3'[Value] )
			    )
			RETURN
			    IF (
			        minDate <> maxDate,
			        CALCULATE (
			            MAX ( 'Goal3'[Value] ),
			            /* 'Goal 3'[UpdatedDate]>minDate && */
			            'Goal3'[UpdatedFromDate] = maxDate
			        ),
			        CALCULATE (
			            MAX ( 'Goal3'[Value] ),
			            'Goal3'[UpdatedFromDate] = maxDate
			        )
			    )
		formatString: 0.00
		lineageTag: 5e43feb6-39c0-4325-8c89-1413901c0f99

	measure Tooltip_color_Goal3 =
			VAR minDate =
			    CALCULATE (
			        MIN ( 'Goal3'[UpdatedFromDate] ),
			        ALLSELECTED ( 'Goal3'[UpdatedFromDate] )
			    )
			VAR maxDate =
			    CALCULATE (
			        MAX ( 'Goal3'[UpdatedFromDate] ),
			        ALLSELECTED ( 'Goal3'[UpdatedFromDate] )
			    )
			VAR minValue =
			    CALCULATE (
			        MAX ( 'Goal3'[Value] ),
			        'Goal3'[UpdatedFromDate] = minDate
			    )
			VAR maxValue =
			    CALCULATE (
			        MAX ( 'Goal3'[Value] ),
			        'Goal3'[UpdatedFromDate] = maxDate
			    )
			VAR countRowsTotal =
			    COUNTROWS (
			        FILTER (
			            'Goal3',
			            'Goal3'[UpdatedFromDate] >= minDate
			                && 'Goal3'[UpdatedFromDate] <= maxDate
			        )
			    )
			RETURN
			    //IF(countRowsTotal>2,IF(minValue<>maxValue,3,0),
			    IF (
			        countRowsTotal >= 2,
			        IF (
			            minValue = maxValue,
			            0,
			            1
			        ),
			        0
			    )
		formatString: 0
		lineageTag: 988d5647-ef4b-4cc2-95fc-6d5a3e8302e0

	column Year
		dataType: double
		formatString: 0
		lineageTag: 20da9a3c-5a6c-4aad-8a54-ceeb216cf526
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: ab82f5b9-51dc-47c0-a91f-1a7ec7931b58
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: e44ebaa2-7f59-4d5b-a6b8-4c0d68aa148a
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: dateTime
		formatString: dd mmmm yyyy
		lineageTag: 5552a7cd-3fcc-4d31-bbd9-803bb4c8366a
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column IndicatorValue
		dataType: string
		lineageTag: 3a9be8dc-1331-4365-9bee-e7fce324c50c
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: b72d8c91-d3c5-4574-976c-ecdce46ebe55
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		lineageTag: b212a56f-73d7-4e5d-819c-585937c4846d
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column Mortality
		dataType: string
		lineageTag: 68a00cb0-6727-4a06-b372-a80123dc98b1
		summarizeBy: none
		sourceColumn: Mortality

		annotation SummarizationSetBy = Automatic

	column nace_r2
		dataType: string
		lineageTag: b5ed3bc2-6e31-40fa-900a-d8d1fdb0b8d9
		summarizeBy: none
		sourceColumn: nace_r2

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: b6946309-18d3-4ade-a3c6-c7d04a5f5c72
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column incgrp
		dataType: string
		lineageTag: 42607abd-723a-44b0-bc21-d24561d61b9f
		summarizeBy: none
		sourceColumn: incgrp

		annotation SummarizationSetBy = Automatic

	column tra_infr
		dataType: string
		lineageTag: 3db7e7a9-fb52-4e28-a7d0-4d98aa9d1124
		summarizeBy: none
		sourceColumn: tra_infr

		annotation SummarizationSetBy = Automatic

	column airpol
		dataType: string
		lineageTag: b8bbe4e2-706c-4845-9d39-7d7cd2927900
		summarizeBy: none
		sourceColumn: airpol

		annotation SummarizationSetBy = Automatic

	column indic_he
		dataType: string
		lineageTag: 795c188b-cbeb-4fb3-8557-9e57fa0cf997
		summarizeBy: none
		sourceColumn: indic_he

		annotation SummarizationSetBy = Automatic

	column icd10
		dataType: string
		lineageTag: 60588eaa-6dbf-42b2-9fdc-c2ce129cd6cd
		summarizeBy: none
		sourceColumn: icd10

		annotation SummarizationSetBy = Automatic

	column sex
		dataType: string
		lineageTag: cf3a69ff-de83-4b06-b6c3-18dea35c28a4
		summarizeBy: none
		sourceColumn: sex

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: double
		lineageTag: 27775bec-b650-4456-85dd-34fb007587c5
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column hhtyp
		dataType: string
		lineageTag: 3c3017c2-8885-4712-a4dd-bc447c0968ed
		summarizeBy: none
		sourceColumn: hhtyp

		annotation SummarizationSetBy = Automatic

	partition Goal3 = m
		mode: import
		queryGroup: 'Goal 3'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"cde5f2dc-94e1-40b1-9d86-7334a30cc33a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 3"]}[Data],
				    Goal3_ = #"cde5f2dc-94e1-40b1-9d86-7334a30cc33a"{[entity="Goal3",version=""]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Goal3_,{{"UpdatedFromDate", type date}, {"Value", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

