table 'Goal 15 Target'
	lineageTag: 30fa17c0-4aca-4c2c-9579-883aba8cfa70

	column TIME_PERIOD
		dataType: int64
		formatString: 0
		lineageTag: 3c2c23e0-bd51-4c86-8aad-7ea0eb4383f6
		summarizeBy: sum
		sourceColumn: TIME_PERIOD

		annotation SummarizationSetBy = Automatic

	column OBS_VALUE
		dataType: double
		lineageTag: 93b71cab-684b-42e9-91bb-c1d71288f7df
		summarizeBy: sum
		sourceColumn: OBS_VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geo
		dataType: string
		lineageTag: 0593ac0c-4743-4684-bb2a-d8403ad4fb44
		summarizeBy: none
		sourceColumn: Geo

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 5dcc8401-729d-42de-94d0-9664c1a3521a
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column landcover
		dataType: string
		lineageTag: d385c3e6-067d-40bf-92c2-46db97d4e546
		summarizeBy: none
		sourceColumn: landcover

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: c4e01cca-36b3-4268-bbd3-29360737fc65
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: c85b994f-655d-4e51-919b-4f96b8320e59
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: aa2ae36c-a4ee-4cb1-af7b-dc7a0631cd23
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Icd10
		dataType: string
		lineageTag: c4c359c7-e8fa-40e5-bc08-7e34eb629889
		summarizeBy: none
		sourceColumn: Icd10

		annotation SummarizationSetBy = Automatic

	column lev_perc
		dataType: string
		lineageTag: 2fd9e844-7609-4266-9e8e-d160ab296db5
		summarizeBy: none
		sourceColumn: lev_perc

		annotation SummarizationSetBy = Automatic

	column leg_stat
		dataType: string
		lineageTag: c1178f0d-405f-4c24-a39e-3e7bd9a43343
		summarizeBy: none
		sourceColumn: leg_stat

		annotation SummarizationSetBy = Automatic

	column OBS_FLAG
		dataType: string
		lineageTag: 15eaf6ed-e995-4bcc-8974-424cc839261b
		summarizeBy: none
		sourceColumn: OBS_FLAG

		annotation SummarizationSetBy = Automatic

	column Partner
		dataType: string
		lineageTag: e94f69e1-f73a-42ca-b36a-2e91039ebd38
		summarizeBy: none
		sourceColumn: Partner
		sortByColumn: 'Partner Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Freq
		dataType: string
		lineageTag: c21b2078-3dbe-4db2-a0dd-d420b7be4b6f
		summarizeBy: none
		sourceColumn: Freq

		annotation SummarizationSetBy = Automatic

	column fin_source
		dataType: string
		lineageTag: 95a61b9e-a5bd-4405-9fdd-aa4192a77afa
		summarizeBy: none
		sourceColumn: fin_source

		annotation SummarizationSetBy = Automatic

	column Sort_Source
		dataType: int64
		formatString: 0
		lineageTag: eb98ca03-143d-4500-98aa-033a382f4c58
		summarizeBy: sum
		sourceColumn: Sort_Source

		annotation SummarizationSetBy = Automatic

	column sitc06
		dataType: string
		lineageTag: fdb413e9-d572-45a7-ae93-53705c226953
		summarizeBy: none
		sourceColumn: sitc06

		annotation SummarizationSetBy = Automatic

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: ec4a9a20-ef46-4029-b0d1-3e6df4d4fc7a
		summarizeBy: sum
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column na_item
		dataType: string
		lineageTag: c1db4ce3-3e7e-46c2-abb2-a5ae731f8ac7
		summarizeBy: none
		sourceColumn: na_item

		annotation SummarizationSetBy = Automatic

	column sector
		dataType: string
		lineageTag: 9ecbf881-ac93-420b-9a33-cfffef41828a
		summarizeBy: none
		sourceColumn: sector

		annotation SummarizationSetBy = Automatic

	column Tax
		dataType: string
		lineageTag: a0ccaa42-ddc1-44b2-b554-9b0da6949e32
		summarizeBy: none
		sourceColumn: Tax

		annotation SummarizationSetBy = Automatic

	column Sex_16_70
		dataType: string
		lineageTag: 1f1a7ec9-c4f4-4f29-a95e-c786d61650bb
		summarizeBy: none
		sourceColumn: Sex_16_70

		annotation SummarizationSetBy = Automatic

	column Perception_Level_16_40
		dataType: string
		lineageTag: 78daf7b4-a610-4a72-b076-e718a5a789f2
		summarizeBy: none
		sourceColumn: Perception_Level_16_40

		annotation SummarizationSetBy = Automatic

	column 'Partner Sort'
		dataType: int64
		formatString: 0
		lineageTag: fda19669-b92d-4432-b5fe-82b7b2080473
		summarizeBy: sum
		sourceColumn: Partner Sort

		annotation SummarizationSetBy = Automatic

	column Statinfo
		dataType: string
		lineageTag: b799a552-eafc-4a9c-af4c-c4fba49e29be
		summarizeBy: none
		sourceColumn: Statinfo

		annotation SummarizationSetBy = Automatic

	column indic_fo
		dataType: string
		lineageTag: 927ec8e1-0600-4353-9068-251d5ed24c9b
		summarizeBy: none
		sourceColumn: indic_fo

		annotation SummarizationSetBy = Automatic

	partition 'Goal 15 Target' = m
		mode: import
		queryGroup: 'Stats-EU Graphs'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"bbfabca1-d350-48fd-8881-823670e9be16" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="All_SDG 15-17"]}[Data],
				    #"Goal 15 Target_" = #"bbfabca1-d350-48fd-8881-823670e9be16"{[entity="Goal 15 Target",version=""]}[Data],
				    #"Added Conditional Column" = Table.AddColumn(#"Goal 15 Target_", "Sex_16_40 ", each if [Sex] = "T" then "Total" else if [Sex] = "F" then "Women" else if [Sex] = "M" then "Men" else null),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Sex_16_40 ", type text}}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Changed Type", "Perception_Level_16_40", each if [lev_perc] = "UNK" then "Don't know" else if [lev_perc] = "VB_FB" then "Very bad or fairly bad" else if [lev_perc] = "VG_FG" then "Very good or fairly good" else null),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Perception_Level_16_40", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Sex_16_40 ", "Sex_16_70"}}),
				    #"Added Conditional Column2" = Table.AddColumn(#"Renamed Columns", "Partner Sort", each if [Partner] = "China (excl. Hong Kong)" then 1 else if [Partner] = "Upper middle income countries" then 2 else if [Partner] = "Lower middle income countries" then 3 else if [Partner] = "Other low income countries" then 4 else if [Partner] = "Least developed countries" then 5 else null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column2",{{"Partner Sort", Int64.Type}}),
				    #"Appended Query" = Table.Combine({#"Changed Type2", SDG_15_11_eu, SDG_17_31_eu})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

