table SDG_14_30
	lineageTag: d09f8517-186b-4b08-bb10-1a74e939226a

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: aa9d7883-28ed-49bf-9842-263cbeacd6a3
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: 63b1d9fd-5bfb-4735-8dc6-a342fa8de3ff
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: string
		isHidden
		lineageTag: 17ea1547-6dbd-420f-b9f6-a0fb70971c5d
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

	column IndicatorValue
		dataType: string
		isHidden
		lineageTag: c4dd16ec-5c50-4d6f-8b3a-a42c18bd7295
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		isHidden
		lineageTag: 2dab4cbd-68c9-4072-baf7-d89ac3cc306f
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column fishreg
		dataType: string
		isHidden
		lineageTag: 824c97c4-0270-46fb-9d89-08b0bdf42271
		summarizeBy: none
		sourceColumn: fishreg

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 395af5a5-4265-4ed5-bf6c-2f4292cd5de0
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column RecordCount
		dataType: double
		lineageTag: 66bc3543-8e8e-442a-8e07-11026a6c559b
		summarizeBy: sum
		sourceColumn: RecordCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SDG_14_30 = m
		mode: import
		queryGroup: 'Goal 14'
		source =
				// let
				//     Source = SharePoint.Tables("https://tmotions0.sharepoint.com/sites/EuroStat_Data", [Implementation=null, ApiVersion=15]),
				//     #"0d3b7721-b3ec-44d5-937d-1fb959c3c236" = Source{[Id="0d3b7721-b3ec-44d5-937d-1fb959c3c236"]}[Items],
				//     #"Renamed Columns" = Table.RenameColumns(#"0d3b7721-b3ec-44d5-937d-1fb959c3c236",{{"ID", "ID.1"}}),
				//     #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"Year", "Value", "RecordCount", "UpdatedFromDate", "UpdatedToDate", "IndicatorValue", "CountryAbrv", "fishreg", "Created"}),
				//     #"Changed Type1" = Table.TransformColumnTypes(#"Removed Other Columns",{{"fishreg", type text}}),
				//     #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"Year", Int64.Type}, {"Value", type number}, {"RecordCount", Int64.Type}, {"UpdatedFromDate", type date}, {"UpdatedToDate", type date}, {"IndicatorValue", type text}, {"CountryAbrv", type text}, {"Created", type date}})
				// in
				//     #"Changed Type"
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"c1cad8c5-2b2f-4168-a09d-4ca007884a11" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 14 to 17"]}[Data],
				    SDG_14_30_ = #"c1cad8c5-2b2f-4168-a09d-4ca007884a11"{[entity="SDG_14_30",version=""]}[Data]
				in
				    SDG_14_30_

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

