table SDG_11_11
	lineageTag: a6dcca8e-a47e-48a8-b5be-cc99561816e4

	column Year
		dataType: int64
		formatString: 0
		lineageTag: fb480521-81fc-490e-b6a2-d11b35e40ff3
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 30ea4c72-d4c2-4b95-b684-6159b28282a9
		summarizeBy: none
		sourceColumn: Unit

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 8deb19d2-e981-4744-a96d-cafe9b94bc03
		summarizeBy: sum
		sourceColumn: Value

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sex
		dataType: string
		lineageTag: f6bce1d0-57bf-4104-a5dc-ea97a8d8df95
		summarizeBy: none
		sourceColumn: sex

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: f00c7085-1bf6-45fa-b872-69ff0bc5a1b0
		summarizeBy: none
		sourceColumn: age

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column UpdatedFromDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 703ae2c7-0dc4-45e1-b7cc-ce249213d4af
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		lineageTag: ba007277-daef-42cb-97d0-b009d7ea6cd5
		summarizeBy: none
		sourceColumn: IndicatorValue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		lineageTag: 058e0fd0-b285-4e58-932c-f32768a61a60
		summarizeBy: none
		sourceColumn: CountryAbrv

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column incgrp
		dataType: string
		lineageTag: 9b6e4c28-7fd7-430c-a908-c50db6e40ca1
		summarizeBy: none
		sourceColumn: incgrp

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cities
		dataType: double
		lineageTag: b8544177-d4fa-40fe-a814-3626fed925c0
		summarizeBy: sum
		sourceColumn: Cities

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Towns and suburbs'
		dataType: double
		lineageTag: 942c8232-f102-40b1-bedb-ce2a73f35f64
		summarizeBy: sum
		sourceColumn: Towns and suburbs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rural areas'
		dataType: double
		lineageTag: e8133e9c-2792-43cc-8aec-aec67eda64ed
		summarizeBy: sum
		sourceColumn: Rural areas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SDG_11_11 = m
		mode: import
		queryGroup: 'Goal 1'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"238281b2-c170-4491-b22a-2ad63536f76a" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 1"]}[Data],
				    SDG_11_11_ = #"238281b2-c170-4491-b22a-2ad63536f76a"{[entity="SDG_11_11",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(SDG_11_11_, each ([incgrp] = "TOTAL")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"UpdatedFromDate", type date}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

