table SDG_09_60
	lineageTag: 18e9fa24-fb14-4414-8f10-5f296fe2517f

	column Year
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b24a7fb6-9531-4002-acde-115b072b5372
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		isHidden
		lineageTag: e90a3b58-fb74-4ff3-bf39-803d4cea88d7
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		isHidden
		lineageTag: d754d70a-71db-4038-b68a-4a9e2004ed79
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UpdatedFromDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 0d8e2040-c903-49d6-b119-987a7b55052d
		summarizeBy: none
		sourceColumn: UpdatedFromDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column IndicatorValue
		dataType: string
		isHidden
		lineageTag: 80259b65-ccf0-4d72-9b14-8e0c81b19126
		summarizeBy: none
		sourceColumn: IndicatorValue

		annotation SummarizationSetBy = Automatic

	column CountryAbrv
		dataType: string
		isHidden
		lineageTag: 543984ee-90b6-4f50-9d29-fc5d16b53659
		summarizeBy: none
		sourceColumn: CountryAbrv

		annotation SummarizationSetBy = Automatic

	column tra_mode
		dataType: string
		isHidden
		lineageTag: 9429d7e0-5339-47c5-b922-89034f165f0a
		summarizeBy: none
		sourceColumn: tra_mode

		annotation SummarizationSetBy = Automatic

	column RecordCount
		dataType: double
		lineageTag: 9fe26383-e08b-466e-b7d9-f37657971a85
		summarizeBy: sum
		sourceColumn: RecordCount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SDG_09_60 = m
		mode: import
		queryGroup: 'Goal 9'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"e7dd114e-bbb6-4bb8-8411-634dc72935be" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="Goal 9"]}[Data],
				    SDG_09_60_ = #"e7dd114e-bbb6-4bb8-8411-634dc72935be"{[entity="SDG_09_60",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(SDG_09_60_, each ([tra_mode] = "RAIL_IWW_AVD")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"UpdatedFromDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

