table SDG_05_11_eu
	lineageTag: 50795a7d-4eb0-4acd-8616-d9643e3ec80b

	column TIME_PERIOD
		dataType: int64
		formatString: 0
		lineageTag: 527081e9-b8ea-4f5c-89d4-5d255276d6cb
		summarizeBy: sum
		sourceColumn: TIME_PERIOD

		annotation SummarizationSetBy = Automatic

	column OBS_VALUE
		dataType: double
		lineageTag: 508cc3f2-a277-43e4-91e0-5942b506e6a7
		summarizeBy: sum
		sourceColumn: OBS_VALUE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Geo
		dataType: string
		lineageTag: 4db0665c-6977-4553-96e2-41bbeafce0be
		summarizeBy: none
		sourceColumn: Geo

		annotation SummarizationSetBy = Automatic

	column Unit
		dataType: string
		lineageTag: 96095826-a264-4064-a04d-605f2ed6abe9
		summarizeBy: none
		sourceColumn: Unit

		annotation SummarizationSetBy = Automatic

	column Freq
		dataType: string
		lineageTag: 940b4cec-3367-49f8-9b93-9432d630da3b
		summarizeBy: none
		sourceColumn: Freq

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: string
		lineageTag: 56aa79d2-5f64-44dd-9168-b62e686b339e
		summarizeBy: none
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Indicator
		dataType: string
		lineageTag: 75cc9ce5-beb3-40f2-9aa9-7e49de3a9d4b
		summarizeBy: none
		sourceColumn: Indicator

		annotation SummarizationSetBy = Automatic

	partition SDG_05_11_eu = m
		mode: import
		queryGroup: 'New indicators 2026'
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"bb4c392e-e6de-4a51-a74f-c2830108781a" = Workspaces{[workspaceId=workspaceID]}[Data],
				    #"2db96d17-b148-4d11-80f4-26b75cb98f00" = #"bb4c392e-e6de-4a51-a74f-c2830108781a"{[dataflowName="ALL_SDG_New Indicators"]}[Data],
				    SDG_05_11_ = #"2db96d17-b148-4d11-80f4-26b75cb98f00"{[entity="SDG_05_11",version=""]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(SDG_05_11_,{{"geo", "Geo"}, {"unit", "Unit"}, {"freq", "Freq"}, {"age", "Age"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Indicator", each "sdg_05_11"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Indicator", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

